package com.example.gymbuddy_tabatatimer

object Constants {
    const val NEW_TABATA_KEY="new tabata"
    const val TABATA_KEY="send tabata"
    const val DB_NAME="db_tabatas"
    const val ALL_TABATAS="all tabatas"
    const val TABATA_ID="tabata id"
    const val PART_ID="tabata part id"
    const val PREP_KEY="prep key"
    const val ROUNDS_KEY="rounds key"
    const val CURRENT_PART="current part"
    const val CURRENT_SET="current set"
    const val CURRENT_ROUND="current round"
    const val IN_BACKGROUND="in background"
    const val TIMER_STARTED="timer started"
    const val TIME_LEFT="time left"
    const val CYCLES="cycles"
    const val PARTS="parts"
    const val CYCLE_TXT="cycles txt"
    const val LOCKED="locked"
    const val TIMER_PAUSED="timer paused"
    const val SYSTEM_TIME="system time"
    const val RESUMED_KEY="resumed"
}